apiVersion: v1
kind: Secret
metadata:
  name: telegram-credentials
type: Opaque
stringData:
  phone_number: "${TELEGRAM_PHONE_NUMBER}"
  api_id: "${TELEGRAM_API_ID}"
  api_hash: "${TELEGRAM_API_HASH}"
