apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-session-storage
  namespace: duke
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
