# AUTOMATICALLY GENERATED by `shtab`

_shtab_telegram_cli_subparsers=('init' 'chats' 'read' 'send' 'edit' 'delete' 'forward' 'reply' 'react' 'click' 'download' 'search-messages' 'search-contacts' 'search-chat' 'info' 'listen')

_shtab_telegram_cli_option_strings=('-h' '--help' '--config')
_shtab_telegram_cli_init_option_strings=('-h' '--help' '--phone')
_shtab_telegram_cli_chats_option_strings=('-h' '--help' '--limit' '--profile' '--bot')
_shtab_telegram_cli_read_option_strings=('-h' '--help' '--from-id' '--to-id' '--forward' '--backward' '--inclusive' '--limit' '--profile' '--bot' '--incoming-only' '--outgoing-only' '--from-user' '--pattern' '--has-media' '--forwarded-only' '--replies-only' '--has-reactions')
_shtab_telegram_cli_send_option_strings=('-h' '--help' '--files' '--reply-to' '--bot')
_shtab_telegram_cli_edit_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_delete_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_forward_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_reply_option_strings=('-h' '--help' '--files' '--target-chat' '--bot')
_shtab_telegram_cli_react_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_click_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_download_option_strings=('-h' '--help' '--bot')
_shtab_telegram_cli_search_messages_option_strings=('-h' '--help' '--limit' '--filter' '--min-date' '--max-date' '--groups-only' '--users-only' '--broadcasts-only' '--profile' '--bot')
_shtab_telegram_cli_search_contacts_option_strings=('-h' '--help' '--limit' '--profile' '--bot')
_shtab_telegram_cli_search_chat_option_strings=('-h' '--help' '--limit' '--filter' '--from-user' '--min-date' '--max-date' '--profile' '--bot')
_shtab_telegram_cli_info_option_strings=('-h' '--help' '--profile' '--bot')
_shtab_telegram_cli_listen_option_strings=('-h' '--help' '--chat' '--private-only' '--mentioned-only' '--profile' '--bot' '--incoming-only' '--outgoing-only' '--from-user' '--pattern' '--has-media' '--forwarded-only' '--replies-only' '--has-reactions')



_shtab_telegram_cli_pos_0_choices=('init' 'chats' 'read' 'send' 'edit' 'delete' 'forward' 'reply' 'react' 'click' 'download' 'search-messages' 'search-contacts' 'search-chat' 'info' 'listen')
_shtab_telegram_cli_search_messages___filter_choices=('photo' 'video' 'document' 'url' 'voice' 'gif' 'music' 'round_video' 'mentions' 'pinned')
_shtab_telegram_cli_search_chat___filter_choices=('photo' 'video' 'document' 'url' 'voice' 'gif' 'music' 'round_video' 'mentions' 'pinned')

_shtab_telegram_cli_pos_0_nargs=A...
_shtab_telegram_cli__h_nargs=0
_shtab_telegram_cli___help_nargs=0
_shtab_telegram_cli_init__h_nargs=0
_shtab_telegram_cli_init___help_nargs=0
_shtab_telegram_cli_chats__h_nargs=0
_shtab_telegram_cli_chats___help_nargs=0
_shtab_telegram_cli_chats___bot_nargs=0
_shtab_telegram_cli_read__h_nargs=0
_shtab_telegram_cli_read___help_nargs=0
_shtab_telegram_cli_read___forward_nargs=0
_shtab_telegram_cli_read___backward_nargs=0
_shtab_telegram_cli_read___inclusive_nargs=0
_shtab_telegram_cli_read___bot_nargs=0
_shtab_telegram_cli_read___incoming_only_nargs=0
_shtab_telegram_cli_read___outgoing_only_nargs=0
_shtab_telegram_cli_read___has_media_nargs=0
_shtab_telegram_cli_read___forwarded_only_nargs=0
_shtab_telegram_cli_read___replies_only_nargs=0
_shtab_telegram_cli_read___has_reactions_nargs=0
_shtab_telegram_cli_send__h_nargs=0
_shtab_telegram_cli_send___help_nargs=0
_shtab_telegram_cli_send___files_nargs=+
_shtab_telegram_cli_send___bot_nargs=0
_shtab_telegram_cli_edit__h_nargs=0
_shtab_telegram_cli_edit___help_nargs=0
_shtab_telegram_cli_edit___bot_nargs=0
_shtab_telegram_cli_delete__h_nargs=0
_shtab_telegram_cli_delete___help_nargs=0
_shtab_telegram_cli_delete___bot_nargs=0
_shtab_telegram_cli_forward__h_nargs=0
_shtab_telegram_cli_forward___help_nargs=0
_shtab_telegram_cli_forward___bot_nargs=0
_shtab_telegram_cli_reply__h_nargs=0
_shtab_telegram_cli_reply___help_nargs=0
_shtab_telegram_cli_reply___files_nargs=+
_shtab_telegram_cli_reply___bot_nargs=0
_shtab_telegram_cli_react__h_nargs=0
_shtab_telegram_cli_react___help_nargs=0
_shtab_telegram_cli_react___bot_nargs=0
_shtab_telegram_cli_click__h_nargs=0
_shtab_telegram_cli_click___help_nargs=0
_shtab_telegram_cli_click___bot_nargs=0
_shtab_telegram_cli_download__h_nargs=0
_shtab_telegram_cli_download___help_nargs=0
_shtab_telegram_cli_download___bot_nargs=0
_shtab_telegram_cli_search_messages__h_nargs=0
_shtab_telegram_cli_search_messages___help_nargs=0
_shtab_telegram_cli_search_messages___groups_only_nargs=0
_shtab_telegram_cli_search_messages___users_only_nargs=0
_shtab_telegram_cli_search_messages___broadcasts_only_nargs=0
_shtab_telegram_cli_search_messages___bot_nargs=0
_shtab_telegram_cli_search_contacts__h_nargs=0
_shtab_telegram_cli_search_contacts___help_nargs=0
_shtab_telegram_cli_search_contacts___bot_nargs=0
_shtab_telegram_cli_search_chat__h_nargs=0
_shtab_telegram_cli_search_chat___help_nargs=0
_shtab_telegram_cli_search_chat___bot_nargs=0
_shtab_telegram_cli_info_pos_0_nargs=+
_shtab_telegram_cli_info__h_nargs=0
_shtab_telegram_cli_info___help_nargs=0
_shtab_telegram_cli_info___bot_nargs=0
_shtab_telegram_cli_listen__h_nargs=0
_shtab_telegram_cli_listen___help_nargs=0
_shtab_telegram_cli_listen___private_only_nargs=0
_shtab_telegram_cli_listen___mentioned_only_nargs=0
_shtab_telegram_cli_listen___bot_nargs=0
_shtab_telegram_cli_listen___incoming_only_nargs=0
_shtab_telegram_cli_listen___outgoing_only_nargs=0
_shtab_telegram_cli_listen___has_media_nargs=0
_shtab_telegram_cli_listen___forwarded_only_nargs=0
_shtab_telegram_cli_listen___replies_only_nargs=0
_shtab_telegram_cli_listen___has_reactions_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_telegram_cli() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_telegram_cli
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    COMPREPLY=( $(compgen -f -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_telegram_cli telegram-cli
